# Book settings
title: From Python to Numpy
author: Nicolas P. Rougier
logo: data/cubes.png



# # Information about where the book exists on the web
# repository:
#   url                       : https://github.com/yourusername/yourbookrepo
#
# # Configure your Binder links, such as the URL of the BinderHub.
# launch_buttons:
#   binderhub_url             : https://mybinder.org
